default:
  image: clojure:tools-deps

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - rm -rf $HOME/.clojure/
    - git clone https://github.com/practicalli/clojure-deps-edn.git $HOME/.clojure/
    - clojure -M:project/uberdeps

test-job:
  stage: test
  script:
    - echo "This job tests something"
    - rm -rf $HOME/.clojure/
    - git clone https://github.com/practicalli/clojure-deps-edn.git $HOME/.clojure/
    - clojure -M:test/cognitect