= hledger-grammars

A set of https://www.antlr.org/[Antlr] grammars for parsing hledger journal formats.
To my knowledge the formats are designed with a manual parser in mind.
The aim of this project is to implement a sub-set good enough so that people can use the tool with journal files that are manually maintained and/or generated by tools.

== Why?

I felt the need to build some grammars for hledger since I wanted to process the formats from other languages.
More specifically I wanted to build some tooling in ClojureScript.

By producing (Antlr) grammars people can parse, validate and convert hledger journal files using a multitude of languages.
Some of them are Clojure, Java and all JVM languages, ClojureScript, JavaScript and all the Nodejs/Browser languages, python, C,C++, etc.
Here is the full list of https://github.com/antlr/antlr4/blob/4.6/doc/targets.md[Antlr 4 target languages and runtimes].

== How to help?

From easiest to hardest:

* Star the project on GitLab https://gitlab.com/ieugen/hledger-grammars
* Share it with our friends
* Improve documentation
* Test the grammar and provide feedback
* Suggest features
* Submit patches

.Status and implementation

|===
| Format | Implementation status | Stability

| timeclock
| yes
| alpha

| timedot
| not planned
| N/A

| journal
| desired
| N/A
|===

.Stability
|===
| Status | Description

| experimental
| Working but maybe incomplete and/or buggy. It is likely to change after feedback.

| beta
| Feature has received attention and is being used with success. Can still change. Not expecting major changes.

| GA
| Feature is working and has been tested by many people. Unlikely to change.

|===

== Installation

Download from https://gitlab.com/ieugen/hledger-grammars

== Usage

Run the project directly:

    $ clojure -M -m ieugen.hledger.grammars

Run the project's tests (they'll fail until you edit them):

    $ clojure -M:test/runner

Build an uberjar:

    $ clojure -X:project/uberjar :main-class ieugen.hledger.grammars

Run that uberjar:

    $ java -jar hledger-grammars.jar

See outdated dependencies

    $ clojure -M:project/outdated

== Options

FIXME: listing of options this app accepts.

== Examples

...

=== Bugs

File an issue.

=== Might be Useful

* https://hledger.org/[Hledger website]
* https://plaintextaccounting.org/[Plain text accounting]


== License

Copyright © 2020 ieugen

Distributed under the Eclipse Public License either version 1.0 or (at
your option) any later version.
