= hledger-grammars

A set of https://www.antlr.org/[Antlr] grammars for parsing hledger journal formats.
To my knowledge the formats are designed with a manual parser in mind.
The aim of this project is to implement a sub-set good enough so that people can use the tool with journal files that are manually maintained and/or generated by tools.

== Installation

Download from https://gitlab.com/ieugen/hledger-grammars

== Usage

Run the project directly:

    $ clojure -M -m ieugen.hledger.grammars

Run the project's tests (they'll fail until you edit them):

    $ clojure -M:test/runner

Build an uberjar:

    $ clojure -X:project/uberjar :main-class ieugen.hledger.grammars

Run that uberjar:

    $ java -jar hledger-grammars.jar

See outdated dependencies

    $ clojure -M:project/outdated

== Options

FIXME: listing of options this app accepts.

== Examples

...

=== Bugs

...

=== Any Other Sections
=== That You Think
=== Might be Useful

== License

Copyright © 2020 Ieugen

Distributed under the Eclipse Public License either version 1.0 or (at
your option) any later version.
